Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (7 given)

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (10 given)

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (10 given)

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (10 given)

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (10 given)

Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (10 given)

Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (10 given)

Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (10 given)

Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (10 given)

Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (7 given)

Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (10 given)

Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (7 given)

Exception in thread Thread-14:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (7 given)

Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (7 given)

Exception in thread Thread-17:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (7 given)

Exception in thread Thread-15:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (7 given)

Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (7 given)

Exception in thread Thread-18:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (8 given)

Exception in thread Thread-19:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (8 given)

Exception in thread Thread-21:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (8 given)

Exception in thread Thread-20:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (7 given)

Exception in thread Thread-22:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (9 given)

Exception in thread Thread-23:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (8 given)

Exception in thread Thread-24:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (7 given)

Exception in thread Thread-25:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (7 given)

Exception in thread Thread-29:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (7 given)

Exception in thread Thread-26:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (8 given)

Exception in thread Thread-28:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (7 given)

Exception in thread Thread-27:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (7 given)

Exception in thread Thread-30:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (7 given)

Exception in thread Thread-32:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (7 given)

Exception in thread Thread-31:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (7 given)

Exception in thread Thread-33:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (7 given)

Exception in thread Thread-34:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (7 given)

Exception in thread Thread-35:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (7 given)

Exception in thread Thread-36:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (7 given)

Exception in thread Thread-37:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (7 given)

Exception in thread Thread-38:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (7 given)

Exception in thread Thread-39:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (7 given)

Exception in thread Thread-41:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (6 given)

Exception in thread Thread-40:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (6 given)

Exception in thread Thread-42:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (6 given)

Exception in thread Thread-43:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (6 given)

Exception in thread Thread-44:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (6 given)

Exception in thread Thread-45:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (6 given)

Exception in thread Thread-46:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (6 given)

Exception in thread Thread-47:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (8 given)

Exception in thread Thread-50:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (6 given)

Exception in thread Thread-48:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (11 given)

Exception in thread Thread-49:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (7 given)

Exception in thread Thread-51:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (6 given)

Exception in thread Thread-53:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (8 given)

Exception in thread Thread-52:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (9 given)

Exception in thread Thread-54:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (7 given)

Exception in thread Thread-56:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (7 given)

Exception in thread Thread-55:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (8 given)

Exception in thread Thread-57:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (7 given)

Exception in thread Thread-60:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (7 given)

Traceback (most recent call last):
  File "./resourceManager.py", line 199, in ?
    main()
  File "./resourceManager.py", line 174, in main
    maintenanceMode()
  File "./resourceManager.py", line 163, in maintenanceMode
    thread.join()
AttributeError: 'NoneType' object has no attribute 'join'
Exception in thread Thread-59:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (7 given)

Exception in thread Thread-58:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (7 given)

Exception in thread Thread-61:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (7 given)

Exception in thread Thread-62:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (7 given)

Exception in thread Thread-63:
Traceback (most recent call last):
  File "/usr/lib/python2.2/threading.py", line 408, in __bootstrap
    self.run()
  File "/usr/lib/python2.2/threading.py", line 396, in run
    apply(self.__target, self.__args, self.__kwargs)
TypeError: releaseResourceWrapper() takes exactly 1 argument (8 given)

